# Generated by Django 4.2.3 on 2023-07-22 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_rename_room_rooms"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="rooms",
            new_name="room",
        ),
    ]
