# Generated by Django 4.2.3 on 2023-07-22 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_rooms_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=10000)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("username", models.CharField(blank=True, max_length=20)),
                ("roomcode", models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
