# Generated by Django 4.2.3 on 2023-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="username",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
