# Generated by Django 4.2.3 on 2023-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_alter_msg_username_alter_room_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="username",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
