# Generated by Django 4.2.3 on 2023-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_alter_msg_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
